baseurl = "https://homes.cs.washington.edu/~bornholt/"
builddrafts = false
canonifyurls = true
uglyurls = true
disablesitemap = true
disablerss = false
metadataformat = "yaml"

pygmentscodefences = true
pygmentsuseclasses = true

[author]
    name = "James Bornholt"
