baseurl = "https://homes.cs.washington.edu/~bornholt/"
builddrafts = true
canonifyurls = false
uglyurls = true
disablesitemap = true
disablerss = false
metadataformat = "yaml"

[author]
    name = "James Bornholt"
